# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Suhith Rajesh
tagline:             I like to build things
url:                 http://blog.suhith.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Suhith Rajesh
  url:               http://suhith.com
  email:             

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/suhithr/blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

future: true